import type { DrugDefinition } from '../domain/models/types';

export const DRUGS: DrugDefinition[] = [
  {
    drugId: 'weed',
    displayName: 'Weed',
    priceBandMin: 80,
    priceBandMax: 420,
    volatilityClass: 'low',
    eventSensitivityClass: 'low',
  },
  {
    drugId: 'coke',
    displayName: 'Coke',
    priceBandMin: 1200,
    priceBandMax: 5200,
    volatilityClass: 'medium',
    eventSensitivityClass: 'medium',
  },
  {
    drugId: 'heroin',
    displayName: 'Heroin',
    priceBandMin: 1500,
    priceBandMax: 6200,
    volatilityClass: 'high',
    eventSensitivityClass: 'high',
  },
  {
    drugId: 'acid',
    displayName: 'Acid',
    priceBandMin: 300,
    priceBandMax: 1900,
    volatilityClass: 'high',
    eventSensitivityClass: 'high',
  },
  {
    drugId: 'speed',
    displayName: 'Speed',
    priceBandMin: 250,
    priceBandMax: 1800,
    volatilityClass: 'high',
    eventSensitivityClass: 'high',
  },
  {
    drugId: 'perc-30s',
    displayName: 'Perc 30s',
    priceBandMin: 900,
    priceBandMax: 4800,
    volatilityClass: 'high',
    eventSensitivityClass: 'high',
  },
  {
    drugId: 'shrooms',
    displayName: 'Shrooms',
    priceBandMin: 350,
    priceBandMax: 1600,
    volatilityClass: 'medium',
    eventSensitivityClass: 'medium',
  },
  {
    drugId: 'hashish',
    displayName: 'Hashish',
    priceBandMin: 180,
    priceBandMax: 700,
    volatilityClass: 'medium',
    eventSensitivityClass: 'medium',
  },
  {
    drugId: 'crack',
    displayName: 'Crack',
    priceBandMin: 120,
    priceBandMax: 1400,
    volatilityClass: 'very-high',
    eventSensitivityClass: 'high',
  },
  {
    drugId: '2cb',
    displayName: '2CB',
    priceBandMin: 1800,
    priceBandMax: 7500,
    volatilityClass: 'very-high',
    eventSensitivityClass: 'very-high',
  },
  {
    drugId: 'ecstasy',
    displayName: 'Ecstasy',
    priceBandMin: 450,
    priceBandMax: 2400,
    volatilityClass: 'high',
    eventSensitivityClass: 'high',
  },
  {
    drugId: 'lean',
    displayName: 'Lean',
    priceBandMin: 500,
    priceBandMax: 2100,
    volatilityClass: 'medium',
    eventSensitivityClass: 'medium',
  },
];

export const DRUG_BY_ID = Object.fromEntries(
  DRUGS.map((drug) => [drug.drugId, drug]),
) as Record<DrugDefinition['drugId'], DrugDefinition>;
