import type { DrugDefinition } from '../domain/models/types';

export const DRUGS: DrugDefinition[] = [
  {
    drugId: 'coke_brick',
    displayName: 'Coke (Brick)',
    unit: '1 Kilo',
    minPrice: 15000,
    maxPrice: 30000,
    normalAvg: 22500,
  },
  {
    drugId: 'heroin',
    displayName: 'Heroin',
    unit: '1 Oz',
    minPrice: 5500,
    maxPrice: 13000,
    normalAvg: 9250,
  },
  {
    drugId: 'two_cb_powder',
    displayName: '2C-B (Powder)',
    unit: '1 Gram',
    minPrice: 1500,
    maxPrice: 4400,
    normalAvg: 2950,
  },
  {
    drugId: 'acid_sheet',
    displayName: 'Acid (Sheet)',
    unit: '100 Tabs',
    minPrice: 1000,
    maxPrice: 4400,
    normalAvg: 2700,
  },
  {
    drugId: 'crack',
    displayName: 'Crack',
    unit: '1 Oz',
    minPrice: 1000,
    maxPrice: 2500,
    normalAvg: 1750,
  },
  {
    drugId: 'shrooms',
    displayName: 'Shrooms',
    unit: '1 Oz',
    minPrice: 630,
    maxPrice: 1300,
    normalAvg: 965,
  },
  {
    drugId: 'hashish',
    displayName: 'Hashish',
    unit: '1 Oz',
    minPrice: 480,
    maxPrice: 1280,
    normalAvg: 880,
  },
  {
    drugId: 'ketamine',
    displayName: 'Ketamine',
    unit: '1 Oz',
    minPrice: 540,
    maxPrice: 1250,
    normalAvg: 895,
  },
  {
    drugId: 'speed',
    displayName: 'Speed',
    unit: '1 Oz',
    minPrice: 315,
    maxPrice: 890,
    normalAvg: 600,
  },
  {
    drugId: 'vape_box',
    displayName: 'Vape Box',
    unit: '1 Box',
    minPrice: 220,
    maxPrice: 700,
    normalAvg: 460,
  },
  {
    drugId: 'weed',
    displayName: 'Weed',
    unit: '1 Oz',
    minPrice: 70,
    maxPrice: 250,
    normalAvg: 160,
  },
  {
    drugId: 'molly',
    displayName: 'Molly',
    unit: '1 Pill',
    minPrice: 11,
    maxPrice: 100,
    normalAvg: 55,
  },
  {
    drugId: 'perc_30s',
    displayName: 'Perc 30s',
    unit: '1 Pill',
    minPrice: 11,
    maxPrice: 60,
    normalAvg: 35,
  },
  {
    drugId: 'lean',
    displayName: 'Lean',
    unit: '1 Pint',
    minPrice: 450,
    maxPrice: 3500,
    normalAvg: 1975,
  },
];

export const DRUG_BY_ID = Object.fromEntries(
  DRUGS.map((drug) => [drug.drugId, drug]),
) as Record<DrugDefinition['drugId'], DrugDefinition>;
